import type { Metadata } from "next";
import { Zap, Palette, Download, Grid3x3, Shield, Layers } from "lucide-react";
import { SeoLanding } from "@/components/landing/SeoLanding";
import { SHOWCASE, isPixelShowcase } from "@/data/showcase";

export const metadata: Metadata = {
  title: { absolute: "Free AI Pixel Art Generator — Retro Game Sprites | SpriteLab" },
  description:
    "Generate pixel art game sprites with AI, snapped to a real pixel grid with a limited palette. 16-bit retro, HD and isometric styles. Free to try.",
  keywords: [
    "pixel art generator",
    "free pixel art maker",
    "AI pixel art",
    "retro game sprites",
    "8-bit sprite generator",
    "16-bit pixel art",
    "game pixel art",
    "pixel art characters",
    "pixel art weapons",
    "indie game art",
  ],
  openGraph: {
    title: "Free AI Pixel Art Generator - Create Game Sprites in Seconds",
    description:
      "Generate pixel art sprites for your games instantly. 8-bit, 16-bit, 32-bit styles. No art skills needed.",
    url: "https://www.sprite-lab.com/pixel-art-generator",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Free AI Pixel Art Generator — Retro Game Sprites | SpriteLab",
    description: "Generate pixel art game sprites with AI, snapped to a real pixel grid with a limited palette. 16-bit retro, HD and isometric styles. Free to try.",
  },
  alternates: {
    canonical: "https://www.sprite-lab.com/pixel-art-generator",
  },
};

const pixelShowcase = SHOWCASE.filter(isPixelShowcase);

export default function PixelArtGeneratorPage() {
  return (
    <SeoLanding
      slug="pixel-art-generator"
      appName="SpriteLab AI Pixel Art Generator"
      appDescription="Generate 8-bit, 16-bit and 32-bit pixel art game sprites from a text prompt. Transparent PNG, commercial license."
      heroLine="ai pixel art generator"
      h1={
        <>
          AI Pixel Art Generator
          <br />
          <span className="text-[#FF8A3D]">sprites in seconds</span>
        </>
      }
      subtitle="Generate 8-bit, 16-bit and 32-bit pixel art sprites for your games. No art skills required — just describe what you want."
      trust={["3 free tries, no account", "10 credits on signup", "transparent png", "real pixel grid"]}
      floating={[
        { src: "/showcase/knight.png", alt: "", pixel: true, cls: "left-[7%] top-[30%] w-24 animate-float" },
        { src: "/showcase/health-potion.png", alt: "", pixel: true, cls: "left-[15%] top-[62%] w-14 animate-float [animation-delay:1.2s]" },
        { src: "/showcase/flame-blade.png", alt: "", pixel: true, cls: "right-[8%] top-[26%] w-24 animate-float [animation-delay:0.6s]" },
        { src: "/showcase/slime.png", alt: "", pixel: true, cls: "right-[15%] top-[60%] w-16 animate-float [animation-delay:1.8s]" },
      ]}
      sections={[
        {
          kind: "cards",
          id: "styles",
          eyebrow: "styles",
          title: (
            <>
              Choose your <span className="text-[#FF8A3D]">pixel style</span>
            </>
          ),
          intro:
            "From classic retro to modern HD pixel art. Sprites are snapped to a real pixel grid with a limited palette — no blurry fake pixels.",
          cards: [
            {
              title: "Pixel 16-bit",
              tag: "8 / 16-bit",
              body: "Classic retro sprites in the spirit of NES, Game Boy and SNES-era games, with a limited color palette.",
              image: { src: "/styles/pixel_art_16.png", alt: "16-bit pixel art knight sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Pixel HD",
              tag: "32-bit",
              body: "Higher-resolution 32-bit pixel art with more detail and shading — the modern indie look.",
              image: { src: "/styles/pixel_art_32.png", alt: "32-bit HD pixel art knight sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Isometric Pixel",
              tag: "iso",
              body: "Isometric pixel art for strategy, tactics and city-builder games — the RTS classic.",
              image: { src: "/styles/isometric_pixel.png", alt: "Isometric pixel art sprite generated by SpriteLab", pixel: true },
            },
          ],
        },
        { kind: "gallery", items: pixelShowcase },
        {
          kind: "features",
          id: "features",
          eyebrow: "features",
          title: (
            <>
              Built for <span className="text-[#FF8A3D]">game-ready</span> pixel art
            </>
          ),
          cards: [
            { icon: Zap, title: "Instant generation", body: "Get your pixel art sprite in seconds — iterate on the prompt until it fits your game." },
            { icon: Palette, title: "Multiple styles", body: "8-bit, 16-bit, 32-bit HD and isometric pixel art — plus 9 more non-pixel styles." },
            { icon: Download, title: "Ready to use", body: "PNG format with transparent backgrounds. Drop it straight into Unity, Godot or GameMaker." },
            { icon: Grid3x3, title: "Real pixel grid", body: "Sprites are stored at native resolution, so they scale up crisply with nearest-neighbour filtering." },
            { icon: Shield, title: "Commercial license", body: "Use what you generate in commercial games on Steam, itch.io or mobile. No attribution required." },
            { icon: Layers, title: "Asset library", body: "Keep every sprite organized by project in your own library once you sign up." },
          ],
        },
        {
          kind: "checklist",
          id: "use-cases",
          eyebrow: "use cases",
          title: (
            <>
              Perfect for <span className="text-[#FF8A3D]">any game</span>
            </>
          ),
          intro: "Generate any type of pixel art asset you need — retro game sprites for platformers, RPGs, roguelikes and more.",
          items: [
            "RPG characters and NPCs",
            "Platformer heroes and enemies",
            "Weapons and equipment",
            "Items and power-ups",
            "Environment tiles",
            "UI icons and buttons",
          ],
        },
        {
          kind: "steps",
          eyebrow: "how it works",
          title: (
            <>
              Three steps. <span className="text-[#FF8A3D]">That&apos;s it.</span>
            </>
          ),
          steps: [
            { title: "Describe your sprite", body: "Write a short prompt — “a goblin archer with a bow, side view”. Colors and materials help." },
            { title: "Pick a pixel style", body: "Choose 16-bit retro, 32-bit HD or isometric pixel art to match your game." },
            { title: "Download the PNG", body: "Get a transparent pixel art PNG, ready for your game engine." },
          ],
        },
      ]}
      faq={[
        {
          q: "Is the AI pixel art generator free?",
          a: "You can try it right on this page without an account. Signing up gives you 10 free credits, no credit card required.",
        },
        {
          q: "Can I make 8-bit and 16-bit pixel art?",
          a: "Yes. The Pixel 16-bit style produces classic retro sprites with a limited palette, Pixel HD gives you more detailed 32-bit pixel art, and Isometric Pixel covers strategy-style views.",
        },
        {
          q: "Can I use the pixel art in commercial games?",
          a: "Yes. You get full ownership of every asset you generate and can use it in any commercial project — Steam, App Store, itch.io, anywhere. No attribution required.",
        },
        {
          q: "What format are the sprites?",
          a: "Sprites export as PNG with a transparent background. Pixel art is kept at its native resolution so you can scale it up crisply in Unity, Godot, GameMaker or any engine.",
        },
      ]}
      cta={{
        title: (
          <>
            Start creating <span className="text-[#FF8A3D]">pixel art</span> today
          </>
        ),
        body: "Build your game faster with AI-generated pixel art — no artists needed.",
        button: "Get 10 free credits",
      }}
    />
  );
}
