import type { Metadata } from "next";
import { SeoLanding } from "@/components/landing/SeoLanding";
import { SHOWCASE } from "@/data/showcase";

export const metadata: Metadata = {
  title: { absolute: "AI Game Weapon Generator | Create Swords, Guns & Magic Items | SpriteLab" },
  description:
    "Generate unique game weapons instantly with AI. Swords, axes, guns, staffs, shields and more. Multiple art styles. Free to try. Perfect for RPGs, action games, and MMOs.",
  keywords: [
    "game weapon generator",
    "AI weapon sprites",
    "sword generator",
    "gun sprite maker",
    "RPG weapon art",
    "fantasy weapons",
    "sci-fi weapons",
    "game item generator",
    "weapon sprites",
    "equipment generator",
  ],
  openGraph: {
    title: "AI Game Weapon Generator - Create Unique Weapons Instantly",
    description:
      "Generate swords, guns, staffs, shields and more for your games. Multiple styles, instant results.",
    url: "https://www.sprite-lab.com/game-weapon-generator",
    type: "website",
  },
  alternates: {
    canonical: "https://www.sprite-lab.com/game-weapon-generator",
  },
};

// Weapons first, then the rest of the curated showcase.
const weaponShowcase = [
  ...SHOWCASE.filter((s) => s.categoryId === "WEAPONS"),
  ...SHOWCASE.filter((s) => s.categoryId !== "WEAPONS"),
];

export default function GameWeaponGeneratorPage() {
  return (
    <SeoLanding
      slug="game-weapon-generator"
      appName="SpriteLab AI Game Weapon Generator"
      appDescription="Generate game weapon sprites — swords, axes, guns, staffs, shields and more — from a text prompt. Transparent PNG, multiple art styles."
      heroLine="ai game weapon generator"
      h1={
        <>
          AI Game Weapon Generator
          <br />
          <span className="text-[#FF8A3D]">forge epic weapons</span>
        </>
      }
      subtitle="Create unique swords, guns, staffs, shields and more for your game. Any style, any fantasy — just describe your weapon."
      trust={["3 free tries, no account", "10 credits on signup", "transparent png", "commercial license"]}
      floating={[
        { src: "/showcase/fire-sword.png", alt: "", pixel: true, cls: "left-[7%] top-[30%] w-24 animate-float" },
        { src: "/showcase/ice-staff.png", alt: "", pixel: true, cls: "left-[14%] top-[60%] w-20 animate-float [animation-delay:1.2s]" },
        { src: "/showcase/flame-blade.png", alt: "", pixel: true, cls: "right-[8%] top-[26%] w-24 animate-float [animation-delay:0.6s]" },
        { src: "/showcase/goblin-archer.png", alt: "", pixel: true, cls: "right-[15%] top-[60%] w-16 animate-float [animation-delay:1.8s]" },
      ]}
      sections={[
        {
          kind: "cards",
          id: "weapon-types",
          eyebrow: "weapon types",
          title: (
            <>
              Every <span className="text-[#FF8A3D]">weapon type</span> you need
            </>
          ),
          intro: "From medieval swords to futuristic laser guns — fantasy weapons, sci-fi weapons and all the equipment in between.",
          cols: 4,
          cards: [
            {
              title: "Melee weapons",
              items: ["Swords", "Axes", "Hammers", "Daggers", "Spears"],
              image: { src: "/showcase/flame-blade.png", alt: "Pixel art flame blade sword sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Ranged weapons",
              items: ["Bows", "Crossbows", "Guns", "Rifles", "Lasers"],
              image: { src: "/showcase/goblin-archer.png", alt: "Pixel art goblin archer with a bow generated by SpriteLab", pixel: true },
            },
            {
              title: "Magic weapons",
              items: ["Staffs", "Wands", "Orbs", "Tomes", "Runes"],
              image: { src: "/showcase/ice-staff.png", alt: "Pixel art ice crystal staff sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Defensive gear",
              items: ["Shields", "Armor", "Helmets", "Gauntlets", "Boots"],
              image: { src: "/showcase/armored-knight.png", alt: "Pixel art armored knight with shield and armor generated by SpriteLab", pixel: true },
            },
          ],
        },
        { kind: "gallery", items: weaponShowcase },
        {
          kind: "cards",
          id: "styles",
          eyebrow: "art styles",
          title: (
            <>
              Multiple <span className="text-[#FF8A3D]">art styles</span>
            </>
          ),
          intro: "Match your game's aesthetic perfectly — the same sword-and-shield prompt, rendered in each style.",
          cards: [
            { title: "Pixel Art", tag: "retro", body: "Retro game style weapon sprites on a real pixel grid.", image: { src: "/styles/pixel_art_16.png", alt: "Pixel art style weapon and armor example", pixel: true } },
            { title: "Dark Fantasy", tag: "grimdark", body: "Grimdark, gritty medieval aesthetic for souls-likes and ARPGs.", image: { src: "/styles/dark_souls.png", alt: "Dark fantasy style sword and shield example" } },
            { title: "Anime", tag: "jrpg", body: "Japanese game art, clean lines — ideal for JRPG weapon art.", image: { src: "/styles/anime_game.png", alt: "Anime style sword and shield example" } },
            { title: "Hand Painted", tag: "painterly", body: "A painterly look for rich item icons and inventory art.", image: { src: "/styles/hand_painted.png", alt: "Hand painted style sword and shield example" } },
            { title: "Realistic", tag: "aaa", body: "AAA concept-art detail — great for sci-fi rifles and futuristic weapons too.", image: { src: "/styles/realistic_painted.png", alt: "Realistic painted style sword and shield example" } },
            { title: "Cartoon", tag: "fun", body: "Fun, colorful style for casual and mobile games.", image: { src: "/styles/cartoon_western.png", alt: "Cartoon style sword and shield example" } },
          ],
        },
        {
          kind: "steps",
          eyebrow: "how it works",
          title: (
            <>
              How it <span className="text-[#FF8A3D]">works</span>
            </>
          ),
          steps: [
            { title: "Describe your weapon", body: "“A flaming sword with dragon engravings” — add materials, colors and mood." },
            { title: "Choose a style", body: "Pick from pixel art, dark fantasy, anime and more to match your game." },
            { title: "Download & use", body: "Get your weapon PNG with a transparent background, ready for your game engine." },
          ],
        },
        {
          kind: "prompts",
          eyebrow: "example prompts",
          title: (
            <>
              Weapon <span className="text-[#FF8A3D]">prompt ideas</span>
            </>
          ),
          intro: "A few starting points for RPGs, action games and MMOs.",
          prompts: [
            "a flaming sword with dragon engravings",
            "an ice crystal staff glowing blue",
            "a rusty double-headed battle axe",
            "a futuristic plasma rifle with neon accents",
            "an elven longbow carved from white wood",
            "a round wooden shield with an iron rim",
          ],
        },
      ]}
      faq={[
        {
          q: "What kinds of weapons can I generate?",
          a: "Melee weapons like swords, axes, hammers, daggers and spears; ranged weapons like bows, crossbows, guns and lasers; magic staffs, wands, orbs and tomes; and defensive gear like shields, armor and helmets.",
        },
        {
          q: "Can I use the weapon sprites in a commercial game?",
          a: "Yes. You get full ownership of every asset you generate and can use it in any commercial project, with no attribution required.",
        },
        {
          q: "Which art styles work best for weapons?",
          a: "Pixel art suits retro and roguelike games, Dark Fantasy fits souls-likes and ARPGs, Anime fits JRPGs, and Hand Painted or Realistic work well for detailed item icons.",
        },
        {
          q: "Is it free to try?",
          a: "Yes. You can try the generator on this page without an account, and signing up gives you 10 free credits — no credit card required.",
        },
      ]}
      cta={{
        title: (
          <>
            Forge your <span className="text-[#FF8A3D]">arsenal</span> today
          </>
        ),
        body: "Stop searching for weapon assets. Generate exactly what you need in seconds.",
        button: "Get 10 free credits",
      }}
    />
  );
}
