import type { Metadata } from "next";
import { SeoLanding } from "@/components/landing/SeoLanding";
import { SHOWCASE } from "@/data/showcase";

export const metadata: Metadata = {
  title: { absolute: "AI RPG Character Creator | Generate Heroes, NPCs & Monsters | SpriteLab" },
  description:
    "Create unique RPG characters with AI. Heroes, villains, NPCs, monsters, and bosses. Multiple fantasy and sci-fi styles. Free to try. Perfect for indie RPG developers.",
  keywords: [
    "RPG character generator",
    "AI character creator",
    "game character sprites",
    "hero generator",
    "NPC generator",
    "monster generator",
    "fantasy characters",
    "RPG sprites",
    "character art",
    "game characters",
  ],
  openGraph: {
    title: "AI RPG Character Creator - Generate Heroes, NPCs & Monsters",
    description:
      "Create unique RPG characters instantly. Heroes, villains, NPCs, monsters in any style.",
    url: "https://www.sprite-lab.com/rpg-character-creator",
    type: "website",
  },
  alternates: {
    canonical: "https://www.sprite-lab.com/rpg-character-creator",
  },
};

// Characters and creatures first, then the rest of the curated showcase.
const isCharacter = (c: string) => c === "CHARACTERS" || c === "CREATURES";
const characterShowcase = [
  ...SHOWCASE.filter((s) => isCharacter(s.categoryId)),
  ...SHOWCASE.filter((s) => !isCharacter(s.categoryId)),
];

const STYLES: { id: string; name: string; tag: string; pixel?: boolean }[] = [
  { id: "pixel_art_16", name: "Pixel 16-bit", tag: "classic retro", pixel: true },
  { id: "pixel_art_32", name: "Pixel HD", tag: "modern indie", pixel: true },
  { id: "hand_painted", name: "Hand Painted", tag: "painterly" },
  { id: "anime_game", name: "Anime", tag: "jrpg" },
  { id: "chibi_cute", name: "Chibi", tag: "cute mobile" },
  { id: "dark_souls", name: "Dark Fantasy", tag: "gritty medieval" },
  { id: "cartoon_western", name: "Cartoon", tag: "expressive" },
  { id: "realistic_painted", name: "Realistic", tag: "aaa concept" },
];

export default function RPGCharacterCreatorPage() {
  return (
    <SeoLanding
      slug="rpg-character-creator"
      appName="SpriteLab AI RPG Character Creator"
      appDescription="Generate RPG character sprites — heroes, villains, NPCs, monsters and bosses — from a text prompt. Transparent PNG, multiple fantasy styles."
      heroLine="ai rpg character creator"
      h1={
        <>
          AI RPG Character Creator
          <br />
          <span className="text-[#FF8A3D]">heroes in seconds</span>
        </>
      }
      subtitle="Generate unique heroes, villains, NPCs and monsters for your RPG. Any class, any race, any fantasy style — just describe your character."
      trust={["3 free tries, no account", "10 credits on signup", "transparent png", "commercial license"]}
      floating={[
        { src: "/showcase/knight.png", alt: "", pixel: true, cls: "left-[7%] top-[30%] w-24 animate-float" },
        { src: "/showcase/slime.png", alt: "", pixel: true, cls: "left-[15%] top-[62%] w-16 animate-float [animation-delay:1.2s]" },
        { src: "/showcase/goblin-archer.png", alt: "", pixel: true, cls: "right-[8%] top-[26%] w-24 animate-float [animation-delay:0.6s]" },
        { src: "/showcase/fox-mage.png", alt: "", cls: "right-[14%] top-[58%] w-20 animate-float [animation-delay:1.8s]" },
      ]}
      sections={[
        {
          kind: "cards",
          id: "character-types",
          eyebrow: "character types",
          title: (
            <>
              Any <span className="text-[#FF8A3D]">character type</span>
            </>
          ),
          intro: "From legendary heroes to terrifying monsters — a hero generator, NPC generator and monster generator in one.",
          cards: [
            {
              title: "Warriors",
              body: "Knights, Barbarians, Samurai, Gladiators",
              image: { src: "/showcase/knight.png", alt: "Pixel art knight warrior RPG sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Mages",
              body: "Wizards, Sorcerers, Witches, Druids",
              image: { src: "/showcase/fox-mage.png", alt: "Chibi fox mage character generated by SpriteLab" },
            },
            {
              title: "Rangers",
              body: "Archers, Hunters, Scouts, Assassins",
              image: { src: "/showcase/goblin-archer.png", alt: "Pixel art goblin archer RPG sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Monsters",
              body: "Dragons, Demons, Undead, Beasts",
              image: { src: "/showcase/slime.png", alt: "Pixel art slime monster sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "NPCs",
              body: "Merchants, Villagers, Guards, Royalty",
              image: { src: "/showcase/armored-knight.png", alt: "Pixel art armored guard NPC sprite generated by SpriteLab", pixel: true },
            },
            {
              title: "Bosses",
              body: "Dark Lords, Ancient Dragons, Liches",
              image: { src: "/styles/dark_souls.png", alt: "Dark fantasy armored knight character generated by SpriteLab" },
            },
          ],
        },
        { kind: "gallery", items: characterShowcase },
        {
          kind: "cards",
          id: "styles",
          eyebrow: "styles",
          title: (
            <>
              One hero, <span className="text-[#FF8A3D]">every style</span>
            </>
          ),
          intro: "The same knight prompt rendered in eight of SpriteLab's art styles — pick the one that fits your RPG.",
          cols: 4,
          cards: STYLES.map((s) => ({
            title: s.name,
            tag: s.tag,
            image: { src: `/styles/${s.id}.png`, alt: `${s.name} style RPG character example`, pixel: s.pixel },
          })),
        },
        {
          kind: "checklist",
          id: "features",
          eyebrow: "features",
          title: (
            <>
              Game-ready <span className="text-[#FF8A3D]">characters</span>
            </>
          ),
          intro: "Everything you need to bring your RPG to life.",
          items: [
            "Full body character sprites",
            "Side, front and top-down views",
            "Idle, A-pose, T-pose or action poses",
            "Consistent style across characters",
            "Transparent backgrounds",
            "HD quality output",
          ],
        },
        {
          kind: "prompts",
          eyebrow: "example prompts",
          title: (
            <>
              Example <span className="text-[#FF8A3D]">prompts</span>
            </>
          ),
          intro: "Copy one into the generator at the top of the page and tweak it for your party.",
          prompts: [
            "A wise elven mage with silver hair and glowing staff",
            "Fierce orc warrior with battle scars and iron armor",
            "Young thief with hood, daggers, and mischievous smile",
            "Ancient dragon boss with purple scales and crown",
            "Friendly merchant gnome with oversized backpack",
            "Dark knight in cursed black armor, red glowing eyes",
          ],
        },
      ]}
      faq={[
        {
          q: "What kinds of RPG characters can I create?",
          a: "Heroes and villains of any class — warriors, mages, rangers — plus NPCs like merchants, villagers and guards, and monsters and bosses such as dragons, demons, undead and liches.",
        },
        {
          q: "Can I use the characters in a commercial game?",
          a: "Yes. You get full ownership of every asset you generate and can use it in any commercial project, with no attribution required.",
        },
        {
          q: "Which styles are available for character sprites?",
          a: "Pixel 16-bit, Pixel HD, Isometric Pixel, Hand Painted, Anime, Chibi, Dark Fantasy, Cartoon, Isometric Cartoon, Isometric, Vector and Realistic.",
        },
        {
          q: "Is the RPG character creator free?",
          a: "You can try it on this page without an account. Signing up gives you 10 free credits, no credit card required.",
        },
      ]}
      cta={{
        title: (
          <>
            Build your <span className="text-[#FF8A3D]">party</span> today
          </>
        ),
        body: "Stop searching for character assets. Create exactly what your RPG needs.",
        button: "Get 10 free credits",
      }}
    />
  );
}
