"use client";

import { useState } from "react";
import Image from "next/image";
import { Sparkles, ChevronLeft, ChevronRight } from "lucide-react";

// Real generated example sprites
const EXAMPLE_SPRITES = [
  {
    id: 1,
    src: "/examples/knight-pixel.png",
    alt: "Pixel art knight",
    prompt: "brave knight in shining armor",
    style: "Pixel Art",
    category: "Characters",
  },
  {
    id: 2,
    src: "/examples/sword-pixel.png",
    alt: "Golden sword",
    prompt: "golden sword with ruby gems",
    style: "Pixel Art",
    category: "Weapons",
  },
  {
    id: 3,
    src: "/examples/slime-cartoon.png",
    alt: "Cute slime monster",
    prompt: "cute slime monster with big eyes",
    style: "Cartoon",
    category: "Creatures",
  },
  {
    id: 4,
    src: "/examples/chest-iso.png",
    alt: "Treasure chest",
    prompt: "treasure chest with gold coins",
    style: "Isometric",
    category: "Items",
  },
  {
    id: 5,
    src: "/examples/dragon-chibi.png",
    alt: "Cute baby dragon",
    prompt: "cute baby dragon breathing flame",
    style: "Chibi Cute",
    category: "Creatures",
  },
  {
    id: 6,
    src: "/examples/mage-anime.png",
    alt: "Mage character",
    prompt: "wizard mage casting spell",
    style: "Anime",
    category: "Characters",
  },
  {
    id: 7,
    src: "/examples/potion-anime.png",
    alt: "Health potion",
    prompt: "health potion with red liquid",
    style: "Anime",
    category: "Items",
  },
  {
    id: 8,
    src: "/examples/shield-realistic.png",
    alt: "Medieval shield",
    prompt: "medieval shield with dragon crest",
    style: "Realistic",
    category: "Equipment",
  },
];

// Placeholder images using a simple colored div
const PlaceholderSprite = ({ color, label }: { color: string; label: string }) => (
  <div
    className={`w-full h-full ${color} flex items-center justify-center`}
    style={{ aspectRatio: "1/1" }}
  >
    <span className="text-white/40 text-xs text-center px-2">{label}</span>
  </div>
);

export function ExamplesGallery() {
  const [activeCategory, setActiveCategory] = useState<string>("All");
  const categories = ["All", "Characters", "Creatures", "Weapons", "Items", "Equipment"];

  const filteredSprites =
    activeCategory === "All"
      ? EXAMPLE_SPRITES
      : EXAMPLE_SPRITES.filter((s) => s.category === activeCategory);

  // Real images are now available in public/examples/
  const hasRealImages = true;

  return (
    <section id="gallery" className="py-16 sm:py-24 relative overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#00d4ff]/5 to-transparent" />

      <div className="max-w-6xl mx-auto px-3 sm:px-4 relative z-10">
        <div className="text-center mb-8 sm:mb-12">
          <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 rounded-full bg-[#00d4ff]/10 border border-[#00d4ff]/20 text-[#00d4ff] text-xs sm:text-sm font-medium mb-4 sm:mb-6">
            <Sparkles className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            Created with SpriteLab
          </div>

          <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold mb-3 sm:mb-4">
            See What <span className="text-[#00d4ff]">Others</span> Created
          </h2>
          <p className="text-white/60 max-w-xl mx-auto text-sm sm:text-base px-2">
            Real sprites generated by our community. Your next game asset could be here!
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-1.5 sm:gap-2 mb-6 sm:mb-8 px-1">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-2.5 sm:px-4 py-1.5 sm:py-2 rounded-full text-xs sm:text-sm font-medium transition-all ${
                activeCategory === category
                  ? "bg-[#00d4ff] text-black"
                  : "bg-white/5 text-white/60 hover:bg-white/10 hover:text-white"
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
          {filteredSprites.map((sprite, index) => (
            <div
              key={sprite.id}
              className="group relative bg-[#0a0a0f]/80 border border-white/10 rounded-xl overflow-hidden hover:border-[#00d4ff]/50 transition-all duration-300 hover:scale-[1.02]"
            >
              {/* Image */}
              <div className="aspect-square relative bg-gradient-to-br from-white/5 to-white/0">
                {hasRealImages ? (
                  <Image
                    src={sprite.src}
                    alt={sprite.alt}
                    fill
                    className="object-contain p-4"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center">
                    <div
                      className="w-3/4 h-3/4 rounded-lg"
                      style={{
                        background: `linear-gradient(135deg, ${
                          ["#00ff88", "#00d4ff", "#ff6b6b", "#ffd93d", "#c084fc", "#ff88cc", "#88ffcc", "#ffaa00"][
                            index % 8
                          ]
                        }20, transparent)`,
                        border: `2px dashed ${
                          ["#00ff88", "#00d4ff", "#ff6b6b", "#ffd93d", "#c084fc", "#ff88cc", "#88ffcc", "#ffaa00"][
                            index % 8
                          ]
                        }40`,
                      }}
                    >
                      <div className="w-full h-full flex flex-col items-center justify-center text-white/30 text-xs text-center p-2">
                        <Sparkles className="w-6 h-6 mb-2 opacity-50" />
                        <span>{sprite.category}</span>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Hover Overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4">
                <p className="text-white text-sm font-medium mb-1 line-clamp-2">
                  &quot;{sprite.prompt}&quot;
                </p>
                <div className="flex items-center gap-2 text-xs text-white/60">
                  <span className="px-2 py-0.5 rounded bg-white/10">{sprite.style}</span>
                  <span>{sprite.category}</span>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <p className="text-white/40 text-sm mb-4">
            Want to see your sprites here? Start creating now!
          </p>
          <a
            href="#try-it"
            className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-[#00ff88] to-[#00d4ff] text-black font-semibold rounded-lg hover:opacity-90 transition-opacity"
          >
            <Sparkles className="w-4 h-4" />
            Try It Free
          </a>
        </div>
      </div>
    </section>
  );
}
