"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { Sparkles, Heart } from "lucide-react";

interface FeaturedSprite {
  id: string;
  imageUrl: string;
  prompt: string;
  style: string;
  category: string;
  likes: number;
}

export function ExamplesGallery() {
  const [activeCategory, setActiveCategory] = useState<string>("All");
  const [sprites, setSprites] = useState<FeaturedSprite[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const categories = ["All", "Characters", "Creatures", "Weapons", "Items", "Equipment"];

  useEffect(() => {
    async function fetchSprites() {
      setLoading(true);
      try {
        const categoryParam = activeCategory !== "All" ? `&category=${activeCategory}` : "";
        const res = await fetch(`/api/featured-generations?limit=12${categoryParam}`);
        const data = await res.json();

        if (data.success && data.generations.length > 0) {
          setSprites(data.generations);
          setError(false);
        } else {
          setSprites([]);
          setError(data.generations?.length === 0);
        }
      } catch {
        setError(true);
        setSprites([]);
      } finally {
        setLoading(false);
      }
    }

    fetchSprites();
  }, [activeCategory]);

  // If no public generations yet, don't show the section
  if (error && sprites.length === 0 && !loading) {
    return null;
  }

  return (
    <section id="gallery" className="py-16 sm:py-24 relative overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#00d4ff]/5 to-transparent" />

      <div className="max-w-6xl mx-auto px-3 sm:px-4 relative z-10">
        <div className="text-center mb-8 sm:mb-12">
          <div className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 rounded-full bg-[#00d4ff]/10 border border-[#00d4ff]/20 text-[#00d4ff] text-xs sm:text-sm font-medium mb-4 sm:mb-6">
            <Sparkles className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
            Created with SpriteLab
          </div>

          <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold mb-3 sm:mb-4">
            See What <span className="text-[#00d4ff]">Others</span> Created
          </h2>
          <p className="text-white/60 max-w-xl mx-auto text-sm sm:text-base px-2">
            Real sprites generated by our community. Your next game asset could be here!
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex flex-wrap justify-center gap-1.5 sm:gap-2 mb-6 sm:mb-8 px-1">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`px-2.5 sm:px-4 py-1.5 sm:py-2 rounded-full text-xs sm:text-sm font-medium transition-all ${
                activeCategory === category
                  ? "bg-[#00d4ff] text-black"
                  : "bg-white/5 text-white/60 hover:bg-white/10 hover:text-white"
              }`}
            >
              {category}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
          {loading ? (
            // Loading skeletons
            [...Array(8)].map((_, i) => (
              <div
                key={i}
                className="relative bg-[#0a0a0f]/80 border border-white/10 rounded-xl overflow-hidden"
              >
                <div className="aspect-square relative bg-gradient-to-br from-white/5 to-white/0 animate-pulse">
                  <div className="w-full h-full flex items-center justify-center">
                    <div className="w-12 h-12 rounded-full border-2 border-white/10 border-t-[#00d4ff] animate-spin" />
                  </div>
                </div>
              </div>
            ))
          ) : sprites.length > 0 ? (
            // Real sprites from database
            sprites.map((sprite) => (
              <div
                key={sprite.id}
                className="group relative bg-[#0a0a0f]/80 border border-white/10 rounded-xl overflow-hidden hover:border-[#00d4ff]/50 transition-all duration-300 hover:scale-[1.02]"
              >
                {/* Image */}
                <div className="aspect-square relative bg-gradient-to-br from-white/5 to-white/0">
                  <Image
                    src={sprite.imageUrl}
                    alt={sprite.prompt.slice(0, 50)}
                    fill
                    className="object-contain p-4"
                    unoptimized // Supabase Storage images
                  />
                </div>

                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4">
                  <p className="text-white text-sm font-medium mb-1 line-clamp-2">
                    &quot;{sprite.prompt}&quot;
                  </p>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs text-white/60">
                      <span className="px-2 py-0.5 rounded bg-white/10">{sprite.style}</span>
                      <span>{sprite.category}</span>
                    </div>
                    {sprite.likes > 0 && (
                      <div className="flex items-center gap-1 text-xs text-pink-400">
                        <Heart className="w-3 h-3" fill="currentColor" />
                        {sprite.likes}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            ))
          ) : (
            // Empty state
            <div className="col-span-full text-center py-12">
              <Sparkles className="w-12 h-12 text-white/20 mx-auto mb-4" />
              <p className="text-white/40">No public sprites in this category yet.</p>
              <p className="text-white/30 text-sm mt-1">Be the first to share your creations!</p>
            </div>
          )}
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <p className="text-white/40 text-sm mb-4">
            Want to see your sprites here? Start creating now!
          </p>
          <a
            href="#try-it"
            className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-[#00ff88] to-[#00d4ff] text-black font-semibold rounded-lg hover:opacity-90 transition-opacity"
          >
            <Sparkles className="w-4 h-4" />
            Try It Free
          </a>
        </div>
      </div>
    </section>
  );
}
