"use client";

import { useState } from "react";
import { Sparkles, Swords, Shield, FlaskConical, Users, PawPrint, Cuboid, ImageIcon, Key, Gem } from "lucide-react";

// Real generated example assets
const EXAMPLE_ASSETS = [
  {
    id: 1,
    prompt: "golden sword with ruby gems",
    style: "Pixel Art",
    category: "Weapons",
    is3D: false,
    image: "/examples/sword-pixel.png",
    fallbackEmoji: "⚔️",
  },
  {
    id: 2,
    prompt: "ice staff with crystal orb",
    style: "Dark Fantasy",
    category: "Weapons",
    is3D: false,
    image: "/examples/staff-dark.png",
    fallbackEmoji: "🪄",
  },
  {
    id: 3,
    prompt: "battle axe with engravings",
    style: "Pixel Art",
    category: "Weapons",
    is3D: false,
    image: "/examples/axe-pixel.png",
    fallbackEmoji: "🪓",
  },
  {
    id: 4,
    prompt: "health potion, red liquid",
    style: "Anime",
    category: "Consumables",
    is3D: false,
    image: "/examples/potion-anime.png",
    fallbackEmoji: "🧪",
  },
  {
    id: 5,
    prompt: "knight helmet with visor",
    style: "Hand Painted",
    category: "Armor",
    is3D: false,
    image: "/examples/helmet-painted.png",
    fallbackEmoji: "🪖",
  },
  {
    id: 6,
    prompt: "medieval shield with dragon",
    style: "Realistic",
    category: "Armor",
    is3D: true,
    image: "/examples/shield-realistic.png",
    fallbackEmoji: "🛡️",
  },
  {
    id: 7,
    prompt: "cute baby dragon",
    style: "Chibi Cute",
    category: "Creatures",
    is3D: false,
    image: "/examples/dragon-chibi.png",
    fallbackEmoji: "🐉",
  },
  {
    id: 8,
    prompt: "cute slime monster",
    style: "Cartoon",
    category: "Creatures",
    is3D: false,
    image: "/examples/slime-cartoon.png",
    fallbackEmoji: "🫠",
  },
  {
    id: 9,
    prompt: "mage casting spell",
    style: "Anime",
    category: "Characters",
    is3D: false,
    image: "/examples/mage-anime.png",
    fallbackEmoji: "🧙",
  },
  {
    id: 10,
    prompt: "knight in shining armor",
    style: "Pixel Art",
    category: "Characters",
    is3D: false,
    image: "/examples/knight-pixel.png",
    fallbackEmoji: "🛡️",
  },
  {
    id: 11,
    prompt: "treasure chest with gold",
    style: "Isometric",
    category: "Items",
    is3D: false,
    image: "/examples/chest-iso.png",
    fallbackEmoji: "📦",
  },
  {
    id: 12,
    prompt: "magic scroll with runes",
    style: "Hand Painted",
    category: "Items",
    is3D: false,
    image: "/examples/scroll-painted.png",
    fallbackEmoji: "📜",
  },
  {
    id: 13,
    prompt: "glowing sapphire gem",
    style: "Vector",
    category: "Resources",
    is3D: false,
    image: "/examples/gem-vector.png",
    fallbackEmoji: "💎",
  },
  {
    id: 14,
    prompt: "golden key with skull",
    style: "Pixel Art",
    category: "Items",
    is3D: false,
    image: "/examples/key-pixel.png",
    fallbackEmoji: "🔑",
  },
];

const FILTERS = [
  { id: "all", label: "All", icon: Sparkles },
  { id: "Weapons", label: "Weapons", icon: Swords },
  { id: "Armor", label: "Armor", icon: Shield },
  { id: "Characters", label: "Characters", icon: Users },
  { id: "Creatures", label: "Creatures", icon: PawPrint },
  { id: "Items", label: "Items", icon: Key },
  { id: "Consumables", label: "Consumables", icon: FlaskConical },
  { id: "Resources", label: "Resources", icon: Gem },
];

export function ExamplesSection() {
  const [filter, setFilter] = useState("all");
  const [imageErrors, setImageErrors] = useState<Record<number, boolean>>({});

  const filteredAssets = filter === "all"
    ? EXAMPLE_ASSETS
    : EXAMPLE_ASSETS.filter(asset => asset.category === filter);

  return (
    <section id="examples" className="py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium mb-4">
            <Sparkles className="w-4 h-4" />
            Community Showcase
          </div>
          <h2 className="text-3xl font-bold mb-4">
            See What You Can Create
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Real examples generated by SpriteLab. Each asset was created in seconds, not hours.
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap justify-center gap-2 mb-8">
          {FILTERS.map((f) => {
            const Icon = f.icon;
            return (
              <button
                key={f.id}
                onClick={() => setFilter(f.id)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all flex items-center gap-2 ${
                  filter === f.id
                    ? "bg-primary text-primary-foreground"
                    : "bg-card border border-border text-muted-foreground hover:text-foreground hover:border-primary/50"
                }`}
              >
                <Icon className="w-4 h-4" />
                {f.label}
              </button>
            );
          })}
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
          {filteredAssets.map((asset) => (
            <div
              key={asset.id}
              className="group relative bg-card border border-border rounded-xl overflow-hidden hover:border-primary/50 transition-all hover:shadow-lg hover:shadow-primary/10"
            >
              {/* Image */}
              <div className="aspect-square bg-muted/30 relative overflow-hidden">
                {!imageErrors[asset.id] ? (
                  <img
                    src={asset.image}
                    alt={asset.prompt}
                    className="w-full h-full object-contain p-4 group-hover:scale-110 transition-transform duration-300"
                    onError={() => setImageErrors(prev => ({ ...prev, [asset.id]: true }))}
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center text-6xl">
                    {asset.fallbackEmoji}
                  </div>
                )}

                {/* 3D Badge */}
                {asset.is3D && (
                  <div className="absolute top-2 left-2 px-2 py-1 rounded-full bg-[#c084fc]/90 text-white text-xs font-bold flex items-center gap-1">
                    <Cuboid className="w-3 h-3" />
                    3D
                  </div>
                )}

                {/* 2D Badge */}
                {!asset.is3D && (
                  <div className="absolute top-2 left-2 px-2 py-1 rounded-full bg-[#00ff88]/90 text-[#030305] text-xs font-bold flex items-center gap-1">
                    <ImageIcon className="w-3 h-3" />
                    2D
                  </div>
                )}

                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-black/70 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                  <div className="text-center p-4">
                    <p className="text-sm text-white font-medium mb-2">&quot;{asset.prompt}&quot;</p>
                    <div className="flex items-center justify-center gap-2">
                      <span className="text-xs px-2 py-1 rounded-full bg-primary/20 text-primary">
                        {asset.style}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Info */}
              <div className="p-3">
                <p className="text-xs text-muted-foreground truncate">
                  {asset.style} • {asset.category}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center mt-12">
          <p className="text-muted-foreground mb-4">
            Ready to create your own game assets?
          </p>
          <a
            href="/register"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-gradient-to-r from-primary to-purple-500 text-primary-foreground font-medium hover:opacity-90 transition-opacity"
          >
            <Sparkles className="w-4 h-4" />
            Start Creating Free
          </a>
        </div>
      </div>
    </section>
  );
}
